//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKS_HotelManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINHLUAN
    {
        public int MaBL { get; set; }
        public Nullable<int> MaPhong { get; set; }
        public Nullable<int> MaKS { get; set; }
        public int MKH { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayBL { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual KHACHSAN KHACHSAN { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
