//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKS_HotelManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTTHUEPHONG
    {
        public int MaThue { get; set; }
        public int KHACH { get; set; }
        public string VaiTro { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual THUEPHONG THUEPHONG { get; set; }
    }
}
