//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKS_HotelManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINHANH
    {
        public int MaHinh { get; set; }
        public Nullable<int> MaPhong { get; set; }
        public Nullable<int> MKH { get; set; }
        public string DuongDan { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayUp { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
