//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKS_HotelManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDDICHVU
    {
        public int MaThue { get; set; }
        public int DV { get; set; }
        public Nullable<int> SoLuot { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual THUEPHONG THUEPHONG { get; set; }
    }
}
