//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKS_HotelManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHTOAN
    {
        public int MaTT { get; set; }
        public int MaThue { get; set; }
        public string HinhThucTT { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public Nullable<System.DateTime> NgayTT { get; set; }
    
        public virtual THUEPHONG THUEPHONG { get; set; }
    }
}
