//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKS_HotelManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANGTHAI_PHONG
    {
        public int MaTrang { get; set; }
        public int MaPhong { get; set; }
        public string TrangThai { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public Nullable<int> MaNVCapNhat { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
